import Head from 'next/head'
import React from 'react'

function HomePage() {
    return (
        <div>
            <Head>
                <title>Clara&apos;sBlog</title>
                <meta name="description" content="Generated by create next app" />
                {/* <link rel="icon" href="/favicon.ico" /> */}
                <link rel="icon" href="/blog.png" />
            </Head>
            <div>Hello</div>
        </div>
    )
}

export default HomePage
